title: Sprint!
hero_image: images/banner.png
description: Use the arrow keys to get to the finish line as quickly as you can.
listed: false
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps: 
- title: Introduction
- title: On your marks...
- title: Going the distance
- title: Who is the fastest?
- title: Adding scenery
- title: 'Challenge: Add a spectator'
  challenge: true
- title: 'What next?'